apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: device-plugins-gpu
  namespace: intel
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 1h
  values:
    sharedDevNum: "2"
