apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: device-plugin-operators
  namespace: intel
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 1h
