apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-storage
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
