apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: 6.18.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      limits_config:
        ingestion_rate_mb: 128
        ingestion_burst_size_mb: 512
        retention_period: "14d"
      compactor:
        retention_enabled: true
    singleBinary:
      replicas: 1
      persistence:
        storageClass: freenas-nfs-csi-no-backup
        size: 125Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: promtail
      version: 6.16.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
