apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      plex:
        defaultContainerOptions:
          resources:
              requests:
                  gpu.intel.com/i915: "1"
              limits:
                  gpu.intel.com/i915: "1"
        containers:
          plex:
            image:
              repository: plexinc/pms-docker
              tag: 1.41.8.9834-071366d65
            env:
              TZ: "America/New_York"
              ADVERTISE_IP: "https://plex.samholton.com:443"
    service:
      plex:
        controller: plex
        ports:
          pms:
            port: 32400
            protocol: TCP
    ingress:
      plex:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host plex.samholton.com
            paths:
              - path: /
                service:
                  identifier: plex
                  port: pms
        tls:
          - hosts:
              - *host
            secretName: plex-tls
    persistence:
      media:
        existingClaim: media-library
      config:
        existingClaim: plex-config
