apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: plex-media-server
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
      interval: 1h
  values:
    ingress:
      enabled: true
      ingressClassName: "nginx-external"
      url: &host "plex.samholton.com"
      tls:
        - hosts:
            - *host
          secretName: plex-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    pms:
      configExistingClaim: plex-config
      resources:
          requests:
              gpu.intel.com/i915: "1"
          limits:
              gpu.intel.com/i915: "1"
    extraEnv:
      TZ: "America/New_York"
    extraVolumes:
      - name: media-library
        persistentVolumeClaim:
          claimName: media-library
    extraVolumeMounts:
     - mountPath: /media
       name: media-library
