kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: freenas-nfs-csi-no-backup
