kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: memos-data
  namespace: memos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: "longhorn"
