apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js
  namespace: zwave-js
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
    controllers:
      main:
        containers:
          main:
            image:
              repository: zwavejs/zwave-js-ui
              tag: 9.33.1
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 10
                  httpGet:
                    httpHeaders:
                    - name: Accept
                      value: text/plain
                    path: /health
                    port: http
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
            resources:
              limits:
                cpu: "1"
                memory: 512Mi
              requests:
                cpu: "1"
                memory: 400Mi
            securityContext:
              privileged: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 8091
          websocket:
            port: 3000
    ingress:
      main:
        className: nginx-internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://zwave-js.samholton.com/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host zwave-js.samholton.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: zwave-js-cert
    persistence:
      zwave-usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0
        advancedMounts:
          main:
            main:
              - path: /dev/zwave
      data:
        existingClaim: zwave-js-data
        advancedMounts:
          main:
            main:
              - path: /usr/src/app/store
