apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-data
  namespace: zwave-js
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
