apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-storage
  namespace: unifi
  labels:
    app: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
