apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: nodered/node-red
              tag: 4.0.5
            env:
              TZ: "America/New_York"
    service:
      main:
        controller: main
        ports:
          http:
            port: 1880
    ingress:
      main:
        className: nginx-internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host node-red.samholton.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: node-red-tls
    persistence:
      data:
        existingClaim: node-red-data
