apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-data
  namespace: node-red
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
