apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-pg
  namespace: paperless
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-secret
  storage:
    storageClass: longhorn
    size: 2Gi
