kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: "freenas-nfs-csi"
