apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pingvin
  namespace: mfp-pingvin
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: stonith404/pingvin-share
              tag: v1.10.2
            env:
              TRUST_PROXY: "true"
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: downloads.myforeverphotos.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - downloads.myforeverphotos.com
            secretName: pingvin-tls
    persistence:
      data:
        existingClaim: pingvin-data
        advancedMounts:
          main:
            main:
              - path: /opt/app/backend/data
