kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pingvin-data
  namespace: mfp-pingvin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: "freenas-nfs-csi"
