apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-pg
  namespace: nextcloud
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-db-secret
  storage:
    storageClass: longhorn
    size: 12Gi
