apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
    namespace: nextcloud
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cKmPM0SVzSnU,iv:hgyZAfIfDPJaEhLwcRrzajO9zs8wvCcXzGR1GdJZjSk=,tag:CxOGARIMaHlOHosU0YGlsw==,type:str]
    password: ENC[AES256_GCM,data:Wq+JLkiGE7DeadplRExs7g==,iv:87kU0pLgFmsvqiSILet8woYTl4pkatqIUYqg4lM9eKg=,tag:RQ0FnUajm3s8s5YEVPSSHg==,type:str]
sops:
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcDRmSHhFOWY4aUs3UUFT
            bFplNW9GOVVkMTlZckJlUEl6S3lqaDNWZEhJCldsSUw2YTF6V2V1bnNHSGo4ajhN
            UjBaWGhzLzVNVEkzVlJEMHNOV3JsN1EKLS0tIGV2aGo2ZTlhMmpUUEZaZ2dBYnNr
            cmdwSDJEc2wvRXorQklEQUs1TXBtY1UKrhHNcO4iy6DhsvjAXbxePSVLCnpEwE4x
            uWm67nHkFj3p9J37oN8MzC5TfedrDKpDSDRyaPuPB6rKjgGXKn2DCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-27T22:17:59Z"
    mac: ENC[AES256_GCM,data:muVIN6uM/DqCpGWbO5FN8ivaLqLbPpCtzxY5UHcCI4jMPThTIVDQw6HF/VEAQo7rHwY/ctcGHkkef8M54OptBRV6LtpxM2g4wP5ZYcBcK9wD/yWTTSZKzyjTAYrSd5gNebsNMK7FE5w0ZttgL5psiUH1pmUbRELh+8NgOsBvWB4=,iv:Kz7nKAj23VEM0lH+l4fsEpz7cVLi27oASSlfVxCx0hg=,tag:RjochtaavYqPxvGXIu+hyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
