apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: mfp-immich
spec:
  imageName: tensorchord/cloudnative-vectorchord:16.9-0.3.0
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  storage:
    storageClass: longhorn
    size: 16Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: mfp-immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-pg
  extensions:
  - name: vchord
    ensure: present
    version: 0.3.0
  - name: earthdistance
    ensure: present
