apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: mfp-immich
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:E8/R8YA9xRr7Xt7P,iv:DUKuysP1fO4diTKCtAmSaufLJbm4pgk/U3AmKSkG+ZI=,tag:wREam8ArWhvR+ctdELvASg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:PnwYYCmH,iv:OjU8wJVwCSF9neK8h49W4K1Sfa4xa14/gtKyofAQXJg=,tag:InCxcWx3mbBgQdS7zMx19w==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:UMRa56loUcvmyi5NVxlYCg==,iv:/pT6+D1NZhKqP0Gr0o6kNFF43GRHp0p+uWwspy8jk8I=,tag:+fnr/jYjcTH6IRAC461nWg==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:FP5JWfS3,iv:Yftts8Vm+SL/5ZgcjjJkPfllhYq9vjd9PjmfkfXsCUY=,tag:uB6UZQe16JxAhZL3yq+0cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUGVaOTFOeGk3eDlYQXVl
            MHNORGxqREczR0VJOGJZbkxpL1hORmxFTEhvCkh5ZlVJeDU2NTNjMzFCZ1BlWnhS
            bDkwRmcwL3p5aWRKWEJlam5ud2xFaXcKLS0tIHpvR0NYYjRDaDdvR0VSMGNDd3oz
            cUQ4aXgzc2RxZEkvellpV2ZjTGFBQncK5RSuC/tWLqWx4w0MUdNSRZK5UzGdXdiQ
            NReS7uYq7AghWrfJTlg+q9Mn1M9hyfl1inqHjuLrwz5Q895XU3uFog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T20:03:14Z"
    mac: ENC[AES256_GCM,data:zZ9UEjC49WdmN5BclBP/cfvJ0UTc5btb4Imllg+lcFROi3+H8jgbzmDLMyFpC7df9yFRgbqn3mNv1GC3Qjb7GD+ex1/gHO1Z0+oGUVBwTjZCZhZGCQxnfZESV0xcuIZz9UhMGQ+iA6cNaVW694+SsS54u7X2k00aPUtuw4PMh6U=,iv:VSEyAUTsdrbQPG/HpFJNAFwyrtbQ4B/YJbrsBAKNC1w=,tag:x7V/gDPKVuWjRyC6QCmanw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
