kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mfp-immich-data
  namespace: mfp-immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: "freenas-nfs-csi"
