apiVersion: v1
kind: Secret
metadata:
    name: rtl433-secret
    namespace: rtl433
type: Opaque
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:1pJiXJ8i4pnEbhr8VQ==,iv:Y9M5r4HmJaoCGBnFRrQ1WBEfYJK4CO9D3C11CVdlLOA=,tag:6ZEn2t9RYLcLlPIrmQ+aWQ==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:OONfvU7SjFSzosNngw==,iv:FBBK3M2i1nELUZXGSiNU/PImlphUZIpn2CDfC9iqBaA=,tag:qcYVI3OCoxOtWy/H1Q8ehw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVDdpSjRyUDhCWFlaclZM
            Q1lTSHZEb3dBblZsN0s3Qzh5eHE4Uyt6MzNFCkQ3ZGI4MFd5UVFiUTVveGE0MzVp
            VG0rRWNRVzZSQ29uKzI0K1RUVWZkVGcKLS0tIG55VUxKRVlqbW8xY1FIK2NHMWti
            NVpiQWdlZ2pQMnBPMXNITUYvaTczSVUKXd6kKZTnVc6X/9vH1pmV+iHj8fKlJ08K
            apO8XngGF532/LzMp0Y19uQeUr7zThugbqWGI9x8sg4hJaBhIiEV1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T19:11:59Z"
    mac: ENC[AES256_GCM,data:3JT5H1Sf+2tMtJ2IiLgw6fvKCzY4Ir/4ryNJxaZ/RfPJ1Dck2a5WS/GGVQ4bXlUjtZvhPvtxL9VmkC4hway5QTmw53D8lvqtInxP8j3z5l5NMDaHAyYMm2+z00+VmHLjHMPD1mEVKOBixh0q4EcqwZUiT4nqXOQc8mPsxbHl/HU=,iv:7e7Oy9zRZd31RUsxzq2l0eY0T9j13GJ/iUGb49hDFeM=,tag:O0wHURWFnQ0MyOLFuhqYuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
