kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: "freenas-nfs-csi"
