apiVersion: v1
kind: Secret
metadata:
    name: sideyardshootout-secret
    namespace: sideyardshootout
type: Opaque
stringData:
    wordpress-password: ENC[AES256_GCM,data:+33ovr5OeJeUSAFBPJ8uc52o,iv:RNodxowCn8jBb2GbH/Lhgu+GYgTRBp9HHElK1D63S2o=,tag:EbyBnw7SIO1TCw2kT0msNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bTdDV1h2SjExOTVwQ0J4
            Unp2eU9jOUkzanFGU3EvY1pZb21wZ1V2NEZNCnlOL1ZqKzZQMlgzenRSYVVhbU5Z
            b0Z3L3NDVkJ2QTlqL2EvZ0lGTmxFeHcKLS0tIG5UVUIyWmd0VXhFSGc0bjVRZ3hK
            VEw3bjQ2U0JnQ0FTd0JScmNucHFCRXcKzqp8SfpfxeoXC/i8JUIv22LqkMifwKY2
            j9/jA9UC5z3Cgprm6YYxIn5oowaXHX/GUGY79eo5C8kOClR4H9kd3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T22:53:56Z"
    mac: ENC[AES256_GCM,data:zBAaAMjV2Yn86gAux0A+M/fBwmIBCAV5y0MjxeFuiH3Dg23aU3nhDNIfJk0bK3sdddAgHUcmafbxKsqc976IQDcw5/yi9IirtN4jtAM0diyYZY3dgyg0b0qP/USaajCODNxr5Y7cUhZll509SNLux/VIkQ3th4DAHU0XPXU55l0=,iv:7OvxQcJnhnqoMiUpYjdw080uUlsaB/tO2ApqHKLeeYM=,tag:vis/q9U4gHICpAT7K4wLYw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
