apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: mealie
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:QsfMS5Az6sdcnWeTnQCA3FSgLxlBf9UGjI+TA87uwJo/nj69MuRzag==,iv:fRlb4/TF7w3SxVK+wkqhDbx0pSu9WjuWKAFPP/J52t0=,tag:qYTe414/vCm9Jp1gqTwKkQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Y6QpaOAWS2d4ZGOmV4b/Un50xJlnhI+wypKskEXOA14TxNupVTeqBI3RAxVIXO837u2ojpNMPTo0FiYsyn1pIEo/mvUFCOAY7OEuOhuz9RWvkbbeG3TPuaq1bDYiLMwG++4gDRKZV+K4wpglkf7Q5OZRBrMpatSQqYasFB76NhM=,iv:WeKi023p4xgvt1KTj/e1GaQlf1D7sJJ1imyN5ruVOV4=,tag:YYYqZaYt4fufhKPj7SIe1Q==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:Ms1AJWNPOpdwNAveFg==,iv:ZRRMIcjQPVtHviLlsoNWN864icr01XOzC9x9NoiBISY=,tag:wqcozR4BaJddkMFAij6oJA==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:fsDZ7z7GnSx2,iv:6VKHysqO3pummkhS2W1u8zUcK2TIMj9talvTRSuhtyw=,tag:MisLfYf4kPwC9Q52uSzNYA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:cN54Y15gMoPGKGbnI4w=,iv:9BMnkCwNCfM9qWoqjjj8qHV5iJxx4V2pxckokpzkQtU=,tag:3d0fJfpH+++ZpDCscfktRQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:1b1g,iv:Jrj+EBcdrfwpyxXl2W73RIxL0OlNeewKZTBX8Tu4Xrg=,tag:IicSWJtSlodIOoa+1edQbQ==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:/roZxtusrQX32iLlWw==,iv:Jp9ZazBcfTTBzOP5MXyGdkffH4kzGAcLOFx1C1sOs3Y=,tag:QrmXv71CsHe+9YDdXy7nXA==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:3ptc,iv:p24t0DDhoIBv2thcgQWsrTYO3XD4WESMq1M7wPANjbQ=,tag:EyRvioqQJsLrg0BiWYsmQQ==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:pwUC3ft2xJG1PTWpe1nNwxNS5XAbCac=,iv:TTToKTHXWZF15NaILC5W4fn/GVG2z8NeL9svXfUl+ws=,tag:cy3fwpoudIG/LFSG1BzY4w==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:0fM5bg5ho6U+L0fwtyY1EQyzdlnnsxs=,iv:3EaJRyM60x11v9SCeLkFsygKufgbN1ddFHAuWjE73Fw=,tag:AEaXSRo8z2zvsQMJ031U+w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:FZ8qJTvknBtRXJ0iPZnCug==,iv:EBExDFZIRNfwU2IuL77KwluWDg9NFpaKmpnp2lXUTno=,tag:zHTQfvRVJ3TFTi4mUUDmFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVDdpSjRyUDhCWFlaclZM
            Q1lTSHZEb3dBblZsN0s3Qzh5eHE4Uyt6MzNFCkQ3ZGI4MFd5UVFiUTVveGE0MzVp
            VG0rRWNRVzZSQ29uKzI0K1RUVWZkVGcKLS0tIG55VUxKRVlqbW8xY1FIK2NHMWti
            NVpiQWdlZ2pQMnBPMXNITUYvaTczSVUKXd6kKZTnVc6X/9vH1pmV+iHj8fKlJ08K
            apO8XngGF532/LzMp0Y19uQeUr7zThugbqWGI9x8sg4hJaBhIiEV1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T02:40:05Z"
    mac: ENC[AES256_GCM,data:r1NxAMzZXALj7uni59qKE9KuBWCFS+wZzzWuaxb/5rY73dRFicQVGrjbjSteDsItti9bOo/LuDcRWEirCPfJaiGk8jvgV55RF+Qd/P22mvTIauht87qTxtbw6Yl18Fdgstytr2vV6qSTcYTUjkU6FwLqbwlniFVhAjpqB87gTjc=,iv:qVEm1/dCTmOd8U3B2pY53hWj6Ihjy2g5VU+FgKvzxNk=,tag:3PXG4+l94Z+lWe2mIpTrVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
