apiVersion: v1
kind: Secret
metadata:
    name: mealie-db-secret
    namespace: mealie
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vtyXYRqw,iv:bsHgHLG2kyiH4HSi1mU8e5wmXPQFPuX4BCRcdafBOhw=,tag:TCERwpo//893VpusPACNYQ==,type:str]
    password: ENC[AES256_GCM,data:RL+2D5yAN9XCZAIPgNELSw==,iv:RwqdpqSiTlIXXF8Eph0cBY8EOAG57idhzndCOxqTBLY=,tag:fYGT4LcGo2FLeiSud7erOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcDRmSHhFOWY4aUs3UUFT
            bFplNW9GOVVkMTlZckJlUEl6S3lqaDNWZEhJCldsSUw2YTF6V2V1bnNHSGo4ajhN
            UjBaWGhzLzVNVEkzVlJEMHNOV3JsN1EKLS0tIGV2aGo2ZTlhMmpUUEZaZ2dBYnNr
            cmdwSDJEc2wvRXorQklEQUs1TXBtY1UKrhHNcO4iy6DhsvjAXbxePSVLCnpEwE4x
            uWm67nHkFj3p9J37oN8MzC5TfedrDKpDSDRyaPuPB6rKjgGXKn2DCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T04:12:13Z"
    mac: ENC[AES256_GCM,data:iWUxKxaVvudLIZYLnWmljlbQCQRBFo4/GN9DIoUXMT3KCV/yg4JiHj95gi3c+p99+/pNbGgTxUiIcuaXory0eHonLKaS1ZOpGyEDNu0+hfVIDXdeXZE5Ndv5L+QbmHnawROC/kvm4w4ObuAlCtPjQsDYYrfwpUOnGXDBs8uIHTU=,iv:V6d4yKCtv/K0qgZzq5o4ShNqEGM3e/ROjLhgqYt8L9U=,tag:+it/dWZ86Xy9+GJkdLpqeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
