apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: mosquitto
type: Opaque
stringData:
    pwfile: ENC[AES256_GCM,data:6JOZcM3MdT4nbceLqf28pLMSrgVC/9buLTPpWjKbbPpGJeoALZAMSp+9IZUJxcZSj+6te1NjfeM1DYqD5p6ltBHF/VlKMyEfM/aY/qvrNx6VlNEyCV492ISnCWMhRx0gRI05YoHCe6EUTSkG29e1FnD3dNGPa69crRoAtIgGFXT/8Rn8lygGQ8OSP84UkL5nk6crpHdhgTO5Yhw/GDIcM9qZjT+ueSZ2OPJQAwIHsZ/J7qDl9sH4QJ3LnRGV160OmIrfZr+gHxB9p3vzWKXS1KwOhm749oP660SzrZEEoZGV7LnLmmVhctu+Z9T9qOzXqqCCdnyRxPeKy9XTHdgek8Pz5pZq2A93xhE36/gkPF5iXfWKvoeaaAUqgYUQT3F7rmj9we7GnC5RVqIaD0gNRaR1vXepqn0p/KyEYHQmy/NfRBoXutJHjCu7xvfCJC+EmL4GahKATm9tcGLHwnA5uXjCzEkFzg==,iv:IAXTIPtUhoYkrmmLOWgRd19kOVKNhxhWChd4OvcY3JM=,tag:LLAWWyvMnw7KBbZQZNKPLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSE9yQXpzRXo0QWRCQ2xP
            VEdWTEgrMG9uam1HUFNmRmFtU0hDcUVLUHlJCnZzcmlIdzYyc1N6Y2VIcTZ4VVdU
            NlIxM05xZ1lkVEtvZDJDSUpjekVRdE0KLS0tIFZKS2pyNGR4Um8vK3pxUTcwTnRz
            UWgzUmdlV2hGRUluc3lpaklhdU1RQkkKgeHtdHB91ZxcFcS/fkt2BSTKorNQSaCA
            RYnqPRudQonv7+ZGQZNL8LBO1yCFheWJF7t1Vq1RPIlM8/Os4y1fvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T15:05:54Z"
    mac: ENC[AES256_GCM,data:WheHvx+S7xj3wmXvyb7blLoasfBIfK60o86chhqHatAlODpaOhu4XR8zEISvXM1zzRGQ49r32Flkv0fNhdFK6VYgFKdU6inT0/WCALEG548g/2cA087DgkeWB1qC/Lf+c+uxdwyRcN9KEidapbuMpbmeceN6LF2yn5ReAqrtHYk=,iv:HY3O4bib8jIADqqOtHyHZDJpqTomUJ5UtVB2cHwwHFE=,tag:dkC3CSZf7Kcze0TVfiL32A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
