apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: erpnext
  namespace: erpnext
spec:
  interval: 1h
  chart:
    spec:
      chart: erpnext
      version: 7.0.176
      sourceRef:
        kind: HelmRepository
        name: frappe
        namespace: flux-system
      interval: 1h
  values:
    persistence:
      worker:
        storageClass: longhorn
    ingress:
      className: "nginx-external"
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: &host erp.samholton.com
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: erpnext-tls
        hosts:
          - *host
    nginx:
      environment:
        upstreamRealIPAddress: "10.244.0.0/16"
    jobs:
      migrate:
        enabled: true
        siteName: *host
