apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder
  namespace: hoarder
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      web:
        containers:
          web:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.21.0
            env:
              MEILI_ADDR: http://hoarder-meilisearch:7700
              BROWSER_WEB_URL: http://hoarder-chrome:9222
              DATA_DIR: /data
              NEXTAUTH_URL: https://hoarder.samholton.com
              DISABLE_SIGNUPS: false
              OAUTH_WELLKNOWN_URL: https://authentik.samholton.com/application/o/hoarder/.well-known/openid-configuration
              OAUTH_PROVIDER_NAME: Holton Cloud Auth
            envFrom:
              - secret: hoarder-secret
      chrome:
        containers:
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
      meilisearch:
        containers:
          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.6
            env:
              MEILI_NO_ANALYTICS: true
    service:
      web:
        controller: web
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    ingress:
      main:
        className: nginx-internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host hoarder.samholton.com
            paths:
              - path: /
                service:
                  identifier: web
                  port: http
        tls:
          - hosts:
              - *host
            secretName: hoarder-tls
    persistence:
      web:
        existingClaim: hoarder-storage
        advancedMounts:
          web:
            web:
              - path: /data
      meilisearch:
        existingClaim: meili-storage
        advancedMounts:
          meilisearch:
            meilisearch:
              - path: /meili_data
