apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-storage
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
