apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-pg
  namespace: home-assistant
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: ha
      owner: ha
      secret:
        name: home-assistant-db-secret
  storage:
    storageClass: longhorn
    size: 16Gi
