apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: homeassistant/home-assistant
              tag: 2025.3.2
            env:
              TZ: America/New_York
    service:
      main:
        controller: main
        ports:
          http:
            port: 8123
      internal:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 192.168.2.11
        ports:
          http:
            port: 8123
    ingress:
      main:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host homeassistant.samholton.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: home-assistant-tls
    persistence:
      data:
        existingClaim: home-assistant-storage
        globalMounts:
          - path: /config
