apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secret
    namespace: home-assistant
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9xE=,iv:SyqOiLLisWLUmG16aT1WP/oIBBsWXuAQPcIGBkUp47A=,tag:eVwBSRWT9SAnIsiJmbM69A==,type:str]
    password: ENC[AES256_GCM,data:zbhyseYUoaFSA6G3BBq5cQ==,iv:BBFoQnAYd0shBUWFnch+jlVMSCNz/MTpZigzk9N1P5o=,tag:nENWIjxX7olhCEJr7Zetww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcDRmSHhFOWY4aUs3UUFT
            bFplNW9GOVVkMTlZckJlUEl6S3lqaDNWZEhJCldsSUw2YTF6V2V1bnNHSGo4ajhN
            UjBaWGhzLzVNVEkzVlJEMHNOV3JsN1EKLS0tIGV2aGo2ZTlhMmpUUEZaZ2dBYnNr
            cmdwSDJEc2wvRXorQklEQUs1TXBtY1UKrhHNcO4iy6DhsvjAXbxePSVLCnpEwE4x
            uWm67nHkFj3p9J37oN8MzC5TfedrDKpDSDRyaPuPB6rKjgGXKn2DCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T02:28:16Z"
    mac: ENC[AES256_GCM,data:fBVYhf3v1cK8fu94Iqm8gJAizvSkKToeDyteGrZIXU5BoB5Uw/5GTjmrzYkd4R/3Pn8ORG6PFsnSXyIueAkZPC94HIV9/qzKp0fdf/tQEJhCgSwbTbjsF7PV5W6zKkJNUCr3mF11RJmLB1++PJhggMAtiMSEJO8/I22C+XKMR/M=,iv:ErG5ymU2T3+ZnAjjZx85IOJJQU9CyX1PUyw93k77hNo=,tag:P4k/KpWc7SncDiOKl45irg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
