apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-storage
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
