apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: mfp-homepage
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/samholton/myforeverphotos
              tag: main
              pullPolicy: Always
        strategy: RollingUpdate
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: myforeverphotos.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
          - host: www.myforeverphotos.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - myforeverphotos.com
              - www.myforeverphotos.com
            secretName: homepage-tls
