apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rallly-pg
  namespace: rallly
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: rallly
      owner: rallly
      secret:
        name: rallly-db-secret
  storage:
    storageClass: longhorn
    size: 2Gi
