apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rallly
  namespace: rallly
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lukevella/rallly
              tag: 4.1.1
            env:
              NEXT_PUBLIC_BASE_URL: https://plan.samholton.com
            envFrom:
              - secret: rallly-secret
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host plan.samholton.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: rallly-tls
