apiVersion: v1
kind: Secret
metadata:
    name: rallly-secret
    namespace: rallly
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:0SHNIPvmrbagxicyHYoj+vK2l37ZGRusNr+9h/i6QkhzxqN9inrT0vsrlTcfpd/OnqDPYY3o,iv:c/eZWONMtIJ1tZ84ebY0EuDcSa4I+U+PPSguDnMBYHE=,tag:tTBrooKz2oxJpnk8kM/zvA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:wrJoisalv5gGKPGSS263g4aLSvNcjdj80aweYt9cDqM=,iv:JwPM4mqt1bWBXj+tjvFM65BMH6mzdcuJlb/OBAyRMQY=,tag:v32nk20smCv1/jwnhSXulQ==,type:str]
    OIDC_NAME: ENC[AES256_GCM,data:BpqRtXY79AqVRTiFGCO9jpQ=,iv:7OULD+9oFJDBymOvWxZ6R3zsZcHQ+vVzPBvrhV+D53U=,tag:RjFltrlMGUdCy7K1Gfjc9g==,type:str]
    OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:VZeYA2GpGHKTY5sNXmkIABl7K7kZ7grZ3J54ECpiFvPupdyJgK7eUdasJJid1sh0DvTLSbQhHZcy0ECNxbkmHMkhWlr5Xp3PTLBVMkf/sBUZ7SRdKw==,iv:pq6TQBVDmrhOHHJOyEkO1ORPzLRkqVf0Mm8Rmmc8M+k=,tag:2JIAr3wcqKdOz2NiKwbDyA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:TDXTmErEnknD4f2kyfci87J6TsYs2hh/ZsVOWX5HxWuI5tBa//Qfyw==,iv:Z3bbDW7OGF6aY0iUqmPtDI8j19Bq61xvJtM3ElrjLos=,tag:sGXtY3xJuOCbgibkb4gvNg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:H+d9L0f1hXjihsUDsLU+OzvngVshlfjSoZgZ6e43rz1NnAzNqsNp8oeJVwcSh1+Mfh9Px1XfwfM97JUwxNDmGEZ87+kZioptsDwOZdq/INIY0NNP8OMvU+irgjDfdpZkaSr35hBPCMNO+vXL7SM0s3sn2qvV1ULiV1JOaQcFsKg=,iv:sKhHD19fVdt/c2EiXOX3vZlab8T0eiGQHCNKT7ggKUo=,tag:L2h7HX1aaLfygstOmE498g==,type:str]
    SUPPORT_EMAIL: ENC[AES256_GCM,data:EDtDidskUdqHF/dP+piCPm4Qmw==,iv:ytUZ83kWP4ZYQZCnPoBAUS4H9bhrDngG0mZZaD5V36w=,tag:MLaIcs8Qi8B+C73HbeWdqQ==,type:str]
    NOREPLY_EMAIL: ENC[AES256_GCM,data:OLsyUnvYN31NF1gLC83Tl84Dy36nBgk=,iv:UJJxmNKTETHMRimhTp0Li9LX0dnUFW2mIqZarMTi/VI=,tag:dbrN4qhLKmnozgTopPiefA==,type:str]
    NOREPLY_EMAIL_NAME: ENC[AES256_GCM,data:jDMCNMM+g9PUSAdxyw==,iv:Ejn7r0E4bGKRW3CfuIeK0kxF9taAb+w7lk9pmp6y4bE=,tag:nsq+YyBnmTDK1DQA3kVE0Q==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:EDzkBYMCayQb+Fjg0rU=,iv:XHR1i930nNeyquWQ8sZB5gUyNybQub8oR5tUn6qqoYc=,tag:P4wFBEhs3YYkyayT8wxqZQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:Wpmr,iv:WadmNePw930N5wRtMHggtC739OfhU9xeuR3AGXd6CPw=,tag:M/lGlb/TA3gxD9VgoypC6w==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:KeWwpA==,iv:ilPNlffdEGpMiSIENMnPgWqS7DOqkegFzP2mjwqO2e4=,tag:038eRQuHpp4eQRbnqENYSA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:9ploOJ2X7j81aL8GBQuOi9l7BFEBX0U=,iv:G6IA1HtzA5YKU3I78en1V/EFup+R1yiiK0i80H2Rf5w=,tag:p2VQfpSZFqko1T+/p3rKgA==,type:str]
    SMTP_PWD: ENC[AES256_GCM,data:OYID48hchgo8aYYYljT9Gw==,iv:2zBr1m/rZQbIPwsku5soACVM/Ti+3U1lHBcS8q1euvU=,tag:V01ht8VG3GbrQ4HhJ2csjg==,type:str]
    SMTP_TLS_ENABLED: ENC[AES256_GCM,data:tdHIQQ==,iv:ZFuRh1UWMgZKFLK0LjUpf4hJlG/5FwFJaeOU8lTSOoI=,tag:p4jN2lA0dkGTcPGRNLnwrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVDdpSjRyUDhCWFlaclZM
            Q1lTSHZEb3dBblZsN0s3Qzh5eHE4Uyt6MzNFCkQ3ZGI4MFd5UVFiUTVveGE0MzVp
            VG0rRWNRVzZSQ29uKzI0K1RUVWZkVGcKLS0tIG55VUxKRVlqbW8xY1FIK2NHMWti
            NVpiQWdlZ2pQMnBPMXNITUYvaTczSVUKXd6kKZTnVc6X/9vH1pmV+iHj8fKlJ08K
            apO8XngGF532/LzMp0Y19uQeUr7zThugbqWGI9x8sg4hJaBhIiEV1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T13:56:14Z"
    mac: ENC[AES256_GCM,data:Pcd0BZb5kRaT3pFO0RLL/D4Kfnpu5LZNhzrYChjGoTRPmXu9tnw5NqERiOqypaMCE5UeMyo8+m23yOyrCIjldr2u3JzcWDaHtGy4t/AgztaK+oe4ddXqLYd81KhL/zPx5sAj/k8XUAlPiXexvUMXcJ0b4YTrYA9eyniE8iS/mtk=,iv:9a1AA1No4XRLoM2dK/0ZoIgy1o6Tp5lZamTFHigUPo8=,tag:fLB1cBAgV9n/7Pv0KpIkEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
