apiVersion: v1
kind: Secret
metadata:
    name: columbuslaserworks-secret
    namespace: columbuslaserworks
type: Opaque
stringData:
    wordpress-password: ENC[AES256_GCM,data:YgSX0egGYrprzWItnkJqDSYjQA==,iv:KqNYHNKfu+d5Jav40GWbFUrFuUeA05KJf133ov+LHjU=,tag:mRzUL4Rpi84/R/UVd7LQqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bTdDV1h2SjExOTVwQ0J4
            Unp2eU9jOUkzanFGU3EvY1pZb21wZ1V2NEZNCnlOL1ZqKzZQMlgzenRSYVVhbU5Z
            b0Z3L3NDVkJ2QTlqL2EvZ0lGTmxFeHcKLS0tIG5UVUIyWmd0VXhFSGc0bjVRZ3hK
            VEw3bjQ2U0JnQ0FTd0JScmNucHFCRXcKzqp8SfpfxeoXC/i8JUIv22LqkMifwKY2
            j9/jA9UC5z3Cgprm6YYxIn5oowaXHX/GUGY79eo5C8kOClR4H9kd3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T20:19:35Z"
    mac: ENC[AES256_GCM,data:6GaG0/GZH0Lu5OSKYekQ72zQE8hjsOw/bTEeqtWc08XLF8i+VYX6QWKbQNJhdAmxCSQn1IpDqgfXpflgUFRjvR8e23Bdp7fQYGyLfNi3BrxGsrpyWJ/n1TEECExVvJynaKtFud9CqCmYxqJhpqApWtQVccJRvNVVOqAle4b1W9o=,iv:cydWnp2mKab73uV7RXVbTieA/aIXD0VIBkJOiWgz/eY=,tag:t1ddoX4WYzm7p93MLNc2PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
