apiVersion: v1
data:
    password: ENC[AES256_GCM,data:PUjVmoaAuPvqavH0,iv:O+vA3o6ny7nT813XrCwwgg06JpgnjNZfHA+Ke7t506s=,tag:xx8TdePGXyj/kCkrUO/d5w==,type:str]
    user: ENC[AES256_GCM,data:ZCevpuLz5io=,iv:vU7Py5JOU7GBkl1+AvmmfQHCzoLqhyavWFbGMDhvO10=,tag:AehM0mkAqwLWMjA/7JuD5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-sop
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rx6m2l3px23zwprh02ahv540uw0ueaq9gvuec3fmalw4w9tnu8qxgy9l0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNHlIL2c4M2NZMEtsZnZs
            aVJlRXpCbTgxMG51SWNkZlVIVEwrZDBqQ0dNCjFhTXN5aDF3ZDlTcHNZSm5vYXJq
            WW5Hbm52NkpYQ1VFSFUrazdxazFlQmsKLS0tIDRNMDR4cG5tN1pzT2ZKMkJ0djFk
            RlJpNW91TFgwbk1sTnlsYk0vZm1sNkEKE25QOeAN8DmBYayZCgiHPzmfcFGZFVAs
            XPX0kCF8vNAfV9CHxNkxMOYW3CCcakPHB+JDzZZh6WM7ys5KZv5HFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-27T21:05:57Z"
    mac: ENC[AES256_GCM,data:brpXtQXIN4sVKTTUKZM+0rtQON1Nh4Y+aNGPvhcG9aJ9q17zbO+FqYhU0g5S4aXq8d89zek/RSx6WIKU91gU0U2OsxRIMVptwdG1fphYFMnZE7ygzV4nmJCLaiE34LZ8hrPlwams6bpPOXdPWug/Wejm9SmxdY5c8Zul152btpQ=,iv:C5MhjTuf8yWEaDs3WnbgbWvFORfRh7jw4LxR2lwbRXU=,tag:DO/uXGtzFzQToKk6iRc5Zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
