---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.11.2'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1h
  values:
    controller:
      allowSnippetAnnotations: true
      electionID: ingress-controller-internal-leader
      ingressClass: &ingressClassInternal nginx-internal
      ingressClassResource:
        name: *ingressClassInternal
      service:
        loadBalancerIP: 192.168.100.8
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx-external
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.11.2'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx-internal
      interval: 1h
  values:
    controller:
      allowSnippetAnnotations: true
      ingressClass: &ingressClassExternal nginx-external
      ingressClassResource:
        name: *ingressClassExternal
      service:
        loadBalancerIP: 192.168.100.7
