---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.12.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1h
  values:
    controller:
      allowSnippetAnnotations: true
      kind: DaemonSet
      electionID: ingress-controller-internal-leader
      ingressClass: &ingressClassInternal nginx-internal
      ingressClassResource:
        name: *ingressClassInternal
        controllerValue: "k8s.io/ingress-nginx-internal"
      service:
        loadBalancerIP: 192.168.100.8
        externalTrafficPolicy: Local
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx-external
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.12.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1h
  values:
    controller:
      allowSnippetAnnotations: true
      kind: DaemonSet
      ingressClass: &ingressClassExternal nginx-external
      ingressClassResource:
        name: *ingressClassExternal
        controllerValue: "k8s.io/ingress-nginx-external"
      service:
        loadBalancerIP: 192.168.100.7
        externalTrafficPolicy: Local
