apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: '4.11.2'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1h
  values:
    controller:
      allowSnippetAnnotations: true
      service:
        loadBalancerIP: 192.168.100.7
